package DCMSApp;


/**
* DCMSApp/DCMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS.idl
* Friday, June 25, 2021 1:35:51 o'clock PM IST
*/

public interface DCMSOperations 
{
  String createTRecord (String firstName, String lastName, String address, String phone, String specialization, String location, String manID);
  String createSRecord (String firstName, String lastName, String courseRegistered, String status, String statusDate, String manID);
  String getRecordCounts (String manID);
  String editRecord (String recID, String fieldName, String newValue, String manID);
  String displayAllRecords (String manID);
  String displayRecord (String manID, String recID);
  String transferRecord (String recID, String toServer, String manID);
  void shutdown ();
} // interface DCMSOperations
