package DCMSApp;


/**
* DCMSApp/DCMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS.idl
* Friday, June 25, 2021 1:35:51 o'clock PM IST
*/

public interface DCMS extends DCMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DCMS
